apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2018-10-21T03:38:47Z
  generation: 2
  labels:
    app: p2pdinner-config-server
  name: p2pdinner-config-server-deployment
  namespace: default
  resourceVersion: "5219"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/p2pdinner-config-server
  uid: d13bd532-d4e2-11e8-96b1-42010a80003b
spec:
  replicas: 5
  selector:
    matchLabels:
      app: p2pdinner-config-server
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: p2pdinner-config-server
    spec:
      containers:
      - image: localhost:5000/config-server
        imagePullPolicy: Always
        name: p2pdinner-config-service
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 5
  conditions:
  - lastTransitionTime: 2018-10-21T03:40:19Z
    lastUpdateTime: 2018-10-21T03:40:19Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
  readyReplicas: 5
  replicas: 5
  updatedReplicas: 5
