---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "p2pdinner-config-server-service-deployment"
  namespace: "default"
  labels:
    app: "p2pdinner-config-server"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8888
  selector:
    app: "p2pdinner-config-server"
  type: "LoadBalancer"
  loadBalancerIP: ""